from pydantic import BaseModel, Field


class TopicInput(BaseModel):
    """
    Request schema for STORM API input.

    Attributes:
        topic (str): The main subject for which a structured outline/article will be generated.
    """
    topic: str = Field(
        ...,  # Required field (no default value)
        example="Artificial Intelligence",  # Example value shown in API docs
        min_length=3,
        max_length=100
    )


class TopicResponse(BaseModel):
    """
    Response schema returned after processing a topic through the STORM pipeline.

    Attributes:
        topic (str): The original input topic.
        outline (dict): The generated outline, which may include questions, summaries, and article sections.
    """
    topic: str  # Echoed input topic
    outline: dict  # Structured content generated by the pipeline
